In [1]:
from pyotc.dataloader.dataloader import AttributedNetworkDataLoader as pyotc_loader

In [2]:
import numpy as np

# Example

P1 = np.array([
    [0.2, 0.5, 0.3],
    [0.1, 0.7, 0.2],
    [0.4, 0.4, 0.2],
], dtype=float)

X1 = np.array([
    [1.0, 10.0],
    [2.0, 20.0],
    [3.0, 30.0],
], dtype=float)

# Network 2 (n=5)
P2 = np.array([
    [0.1, 0.2, 0.2, 0.2, 0.3],
    [0.3, 0.1, 0.2, 0.2, 0.2],
    [0.2, 0.2, 0.1, 0.2, 0.3],
    [0.2, 0.2, 0.2, 0.1, 0.3],
    [0.2, 0.2, 0.2, 0.2, 0.2],
], dtype=float)

X2 = np.array([
    [0.0,  5.0],
    [1.0, 15.0],
    [2.0, 25.0],
    [3.0, 35.0],
    [4.0, 45.0],
], dtype=float)

# Network 3 (n=4)
P3 = np.array([
    [0.25, 0.25, 0.25, 0.25],
    [0.3,  0.2,  0.3,  0.2 ],
    [0.2,  0.3,  0.2,  0.3 ],
    [0.1,  0.4,  0.3,  0.2 ],
], dtype=float)

X3 = np.array([
    [5.0,  1.0],
    [6.0,  2.0],
    [7.0,  3.0],
    [8.0,  4.0],
], dtype=float)

P_train = [P1, P2, P3]
X_train = [X1, X2, X3]
y_train = [0, 1, 0]   # make sure order matches P_train / X_train


P4 = np.array([
    [0.6, 0.4],
    [0.3, 0.7],
], dtype=float)

X4 = np.array([
    [10.0, 100.0],
    [20.0, 200.0],
], dtype=float)

P5 = np.array([
    [0.2, 0.2, 0.2, 0.2, 0.1, 0.1],
    [0.1, 0.3, 0.2, 0.2, 0.1, 0.1],
    [0.2, 0.2, 0.2, 0.2, 0.1, 0.1],
    [0.2, 0.2, 0.1, 0.2, 0.2, 0.1],
    [0.1, 0.2, 0.2, 0.2, 0.2, 0.1],
    [0.2, 0.1, 0.2, 0.2, 0.2, 0.1],
], dtype=float)

X5 = np.array([
    [1.0,  11.0],
    [2.0,  22.0],
    [3.0,  33.0],
    [4.0,  44.0],
    [5.0,  55.0],
    [6.0,  66.0],
], dtype=float)

P_test = [P4, P5]
X_test = [X4, X5]

In [18]:
# Build loader

dl = pyotc_loader.from_lists(
    p=2,
    P_train=P_train,
    X_train=X_train,
    y_train=y_train,
    P_test=P_test,
    X_test=X_test,
)

print("Number of train networks:", len(dl.train_loader()))
print("Number of test networks:", len(dl.test_loader()))

[Warning/train] Please make sure P, X, y are sorted/aligned in the SAME order for the train split.
[Warning/test] Please make sure P, X are sorted/aligned in the SAME order for the test split.
Number of train networks: 3
Number of test networks: 2


In [19]:
train_graph = dl.train_loader()

In [20]:
train_example = train_graph[0]

In [21]:
train_example.y

0

In [22]:
# Compute cost matrices

costs = dl.calculate_cost(
    within_train=True,
    train_test=True,
    within_test=True,
)

In [23]:
costs["within_train"][1][(1,2)]

array([[1.600e+01, 9.000e+00, 4.000e+00, 1.000e+00],
       [1.960e+02, 1.690e+02, 1.440e+02, 1.210e+02],
       [5.760e+02, 5.290e+02, 4.840e+02, 4.410e+02],
       [1.156e+03, 1.089e+03, 1.024e+03, 9.610e+02],
       [1.936e+03, 1.849e+03, 1.764e+03, 1.681e+03]])

In [24]:
costs["within_test"][1][(0,1)]

array([[ 7921.,  6084.,  4489.,  3136.,  2025.,  1156.],
       [35721., 31684., 27889., 24336., 21025., 17956.]])

In [25]:
costs["train_test"][1][(0,1)]

array([[1.000e+00, 1.440e+02, 5.290e+02, 1.156e+03, 2.025e+03, 3.136e+03],
       [8.100e+01, 4.000e+00, 1.690e+02, 5.760e+02, 1.225e+03, 2.116e+03],
       [3.610e+02, 6.400e+01, 9.000e+00, 1.960e+02, 6.250e+02, 1.296e+03]])